services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data:/data/db

  app:
    container_name: app
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_started

volumes:
  mongodb_data:
